######################################################################
# Automatically generated by qmake (2.01a) ?? 12? 7 14:12:51 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
